### ISSUE TITLE
some question about Training_ML_LSTM.py

### ISSUE THREAD

**Issue by t109318123** [Aminullah6264/Activity_Rec_ML-LSTM#1]
I have finished the Features_Extraction.py, and I  faced some problems in executing the Training_ML_LSTM.py . I couldn't find YouTubeActions_TotalFeatures and DatabaseLabel in line 17. I want to make sure which format of the file I could select (UCF50_Labels.mat && UCF50_TotalFeatures.npy), thanks.

**Comment by aminullah6264** [comment]
You can see line 178 to line 181... your extracted features are saved with these names in the same folder. 

(YouTubeActions_TotalFeatures,DatabaseLabel) are basically the extracted features and labels names, so you have to first load them before train and test split.

You can use scipy.io.loadmat for loading the features...

**Comment by t109318123** [comment]
Thanks, this is helpful for me.
